### ISSUE TITLE
Addition to the language selection

### ISSUE THREAD

**Issue by jrg89** [balsimpson/node-red-contrib-wavenet#1]
Hi,

Thank you creating this, it's been a really useful integration to my Home Assistant automations!

Is it possible to add the ability to select the voice that is used? With the current language selection, it will randomly select a voice (where multiple are available) and it would be great to have a consistent voice for notifications

**Comment by balsimpson** [comment]
Am glad it's been useful for you. Have simplified the options and now you can choose a specific voice or a random voice. Let me know if it works for you.

**Comment by jrg89** [comment]
This works perfectly and much simpler than what I was going to suggest...

Thanks for making the update!
