### ISSUE TITLE
More languages

### ISSUE THREAD

**Issue by MTrab** [balsimpson/node-red-contrib-wavenet#4]
Please add all languages - or at least let us input which language we want.
Specifically I need the Danish voice.

**Comment by balsimpson** [comment]
Have added Danish Female voice which is the only one available as Wavenet. If it works, please let me know.

**Comment by MTrab** [comment]
Can't see the update in my NodeRed - latest available is 1.5.0.
I'll take a look again later.

**Comment by balsimpson** [comment]
![image](https://user-images.githubusercontent.com/16057289/70995829-7890fc00-20f7-11ea-8216-58a09f4bf416.png)
The latest version is 2.5.1
It's showing up on my Node-RED

**Comment by MTrab** [comment]
Unfortunately still nothing in mine, and I don't know how I force it to search for updates.

![Udklip](https://user-images.githubusercontent.com/14296463/71003975-b71bbc00-20e1-11ea-909f-ccc3963b2057.PNG)

**Comment by balsimpson** [comment]
Are you running it on a Pi? then you can go to `/home/pi/.nodered` and then run the command `npm install node-red-contrib-wavenet@2.5.1`

**Comment by MTrab** [comment]
The update was present when I got home :) Thank you.
